[package]
name = "appvis"
version = "0.1.0"
edition = "2021"
description = "manage application launch timing"

[package.metadata.bundle]
identifier = "io.github.earlgray283.appvis"
icon = ["./assets/icon.png"]

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
tao = "0.26"
tray-icon = "0.11"
tokio = { version = "1.36", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
image = "0.24"
toml = "0.8"
serde = "1.0"
